### PR TITLE
Updated readme info to be kss-rails-alan, kss-rails didnt seem to work.

### PR DESCRIPTION
**Pull request by curiouslychase**
Was getting an error with kss-rails, changed the gem to the other kss-rails and it worked:

http://rubygems.org/gems/kss-rails-alan

### CODE REVIEW

**Comment by dewski** [comment]
This PR would render this gem useless ;) What error were you getting on `kss-rails`? It would be helpful if you opened up an issue with it so I can fix it on this repository as [kss-rails-alan](https://github.com/alanhogan/kss-rails) is a completely separate repository.

**Comment by curiouslychase** [comment]
Yeah...good call closing it. For some reason I was getting a weird error originally, once I added the version from 

https://rubygems.org/gems/kss-rails

~> 1.0.1

Worked like a charm. My bad. :D

**Comment by dewski** [comment]
No worries, happy documenting :zap:

**Comment by alanhogan** [comment]
Huh, funny. Happily, all my kss-rails pull requests were merged upstream :)

**Pull request closed without merging**
